### PR TITLE
Feature/export-improvement

### PR DESCRIPTION
**Pull request by paga16-hash**
- add possibility to export CNF in DIMACS format
- add header to exported file 
- fix z index file chooser for export
- fix relatives tests adding the header
- add documentation in system and user requirements
- fix parse function @w-disaster  take a look to the buildOrCNF method and check for my modification, tell me also if i have to introduce it also in buildAndCNF, thanks :D

### CODE REVIEW

**Review by w-disaster — CHANGES_REQUESTED** [review]
I did a typo in #86, there were two commented methods, they're the correct `buildOrCNF` and `buildAndCNF`:

```
private def buildOrCNF(cnf: Seq[Literal]): Or | Literal =
    cnf.tail.foldLeft[Or | Literal](cnf.head)((p, c) => Or(c, p))

private def buildAndCNF(cnf: Seq[Or | Literal]): And | Or | Literal =
    cnf.tail.foldLeft[And | Or | Literal](cnf.head)((p, c) => And(c, p))
```

can you replace them?

**Comment by paga16-hash** [comment]
> I did a typo in #86, there were two commented methods, they're the correct `buildOrCNF` and `buildAndCNF`:
> 
> ```
> private def buildOrCNF(cnf: Seq[Literal]): Or | Literal =
>     cnf.tail.foldLeft[Or | Literal](cnf.head)((p, c) => Or(c, p))
> 
> private def buildAndCNF(cnf: Seq[Or | Literal]): And | Or | Literal =
>     cnf.tail.foldLeft[And | Or | Literal](cnf.head)((p, c) => And(c, p))
> ```
> 
> can you replace them?

Of course!

**Comment by paga16-hash** [comment]
> > I did a typo in #86, there were two commented methods, they're the correct `buildOrCNF` and `buildAndCNF`:
> > ```
> > private def buildOrCNF(cnf: Seq[Literal]): Or | Literal =
> >     cnf.tail.foldLeft[Or | Literal](cnf.head)((p, c) => Or(c, p))
> > 
> > private def buildAndCNF(cnf: Seq[Or | Literal]): And | Or | Literal =
> >     cnf.tail.foldLeft[And | Or | Literal](cnf.head)((p, c) => And(c, p))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can you replace them?
> 
> Of course!

done, thank you

**Review by w-disaster — APPROVED** [review]
Well done! :)

**Review by Mala1180 — APPROVED** [review]

**Pull request merged**
